language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - '10'
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - if [[ $TRAVIS_BRANCH =~ release/* ]]; then ./script/version.sh; else ./script/publish.sh; fi
