language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - '10'
env:
  - GIT_USER=zack9433
script:
  - ./scripts/version.sh

after_success:
  - yarn travis-deploy-once "yarn release"
branches:
  only:
    - master
