language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - '10'
script:
  - yarn --cwd ./website build

after_success:
  - yarn travis-deploy-once "yarn release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
