language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - '10'
deploy:
  - provider: script
    script: bash scripts/version.sh
    on:
      branch: release/*
  - provider: script
    script: bash scripts/publish.sh
    on:
      branch: master
